### ISSUE TITLE
Publish Minor/Major/Critical counts for viewing in Statistics graphs

### ISSUE THREAD

**Issue by slolife** [kunalkanojia/tasks-teamcity-plugin#2]
Publish Minor/Major/Critical counts for viewing in Statistics graphs

Is there a way to add a graph to the Statistics tab from a plugin?

**Comment by kunalkanojia** [comment]
No, there is no way currently to create a graph. Good point though, I think it will be a nice to have. Will try and take time out to do it. PR's are definitely welcome.

**Comment by slolife** [comment]
I've never done java or Kotlin, so while I'll take a look to see if I can get the plugin building locally, I don't know how long that will take.

I now understand that a graph cannot be "added" via a plugin.  But if the plugin dumps some important numbers into the build statistics, the graph could be later added manually

https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildStatisticsReportingBuildStatistics

Again, I'll try to get it building so I can take a stab at it.

**Comment by kunalkanojia** [comment]
@slolife Took a look and thanks your link it looked simple enough. I made the required changes and updated the plugin. (Attached screenshot)
